name:                Brainfxck-interpreter
version:             0.1.0.0
github:              4afS/Brainfxck-interpreter
license:             BSD3
author:              4afS
maintainer:          4afs.h1@gmail.com
copyright:           2019 4afS

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/4afS/Brainfxck-interpreter#readme>

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.8.0
- haskeline >= 0.7
- mtl

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  Brainfxck-interpreter-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - Brainfxck-interpreter

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  Brainfxck-interpreter-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - Brainfxck-interpreter
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
